### ISSUE TITLE
Submit score to leaderboard

### ISSUE THREAD

**Issue by SparedRay** [ludei/atomic-plugins-googleplaygames#3]
I have a problem trying to submit a score to Google play games leaderboard but it doesnt work, i have the following code:
```javascript
social.submitScore({
    score,
    function(error) { if(error) { console.log("there was an error: " + error) } },
    {leaderboardID: Unlockable[Game.map]},
});
```
where ```score``` is a number and ```Unlockable[Game.map]``` is the string with the leaderboard id provided by Google play games. All other functions (like showing the leaderboard) works without a problem so i dont know what could be wrong.

From the console i only get:
```there was an error: Invalid Action```

**Comment by SparedRay** [comment]
More info about the log:
```
System.err: java.lang.reflect.InvocationTargetException
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.ludei.googleplaygames.cordova.GPGPlugin.execute(GPGPlugin.java:43)
System.err: 	at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:117)
System.err: 	at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
System.err: 	at org.apache.cordova.PluginManager.exec(PluginManager.java:133)
System.err: 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
System.err: 	at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
System.err: 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
System.err: 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:41)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:111)
System.err: 	at android.os.Looper.loop(Looper.java:207)
System.err: 	at android.os.HandlerThread.run(HandlerThread.java:61)
System.err: Caused by: org.json.JSONException: Value null at 0 of type org.json.JSONObject$1 cannot be converted to long
System.err: 	at org.json.JSON.typeMismatch(JSON.java:100)
System.err: 	at org.apache.cordova.CordovaArgs.getLong(CordovaArgs.java:61)
System.err: 	at com.ludei.googleplaygames.cordova.GPGPlugin.submitScore(GPGPlugin.java:224)
System.err: 	... 12 more
```

**Comment by mentuat** [comment]
looking at the source the format for  submitScore seems to be:

`submitScore: function(score, leaderboardID, callback)`

**Comment by SparedRay** [comment]
Done, it was an error on other part of my code, but still documentation should be updated since it says leaderboard id should be a number but google play gives me a string.
